In [1]:
#Importación de librerías
import pandas as pd
import numpy as np
import re
import nltk
import spacy
import matplotlib.pyplot as plt
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer
from spacy import displacy
from nltk.stem import SnowballStemmer

import warnings
warnings.filterwarnings('ignore')

nlp = spacy.load("es_core_news_lg")
stopwords = nltk.corpus.stopwords.words('english')

In [9]:
datos = pd.read_csv(r'C:\Users\Alejandro\OneDrive\Escritorio\ANE\Data\tripadvisor_hotel_reviews.csv')
datos.head()

                                              Review  Rating
0  nice hotel expensive parking got good deal sta...       4
1  ok nothing special charge diamond member hilto...       2
2  nice rooms not 4* experience hotel monaco seat...       3
3  unique, great stay, wonderful time hotel monac...       5
4  great stay great stay, went seahawk game aweso...       5

In [10]:
sentences = datos['Review'].head(2000)

### Analisis de Sentimientos

In [11]:
from nltk.sentiment.vader import SentimentIntensityAnalyzer
from nltk import sentiment
from nltk import word_tokenize

In [12]:
def anal_sent(sentences):
    analizador = SentimentIntensityAnalyzer()
    lista = []
    for sentence in sentences:
        lista.append(analizador.polarity_scores(sentence))
    
    dataframe = pd.DataFrame(lista)
    return dataframe.mean()

In [13]:
datos4 = datos[datos['Rating'] == 4]
sentences4 = datos4['Review'].head(2000)

In [14]:
anal_sent(sentences4)

neg         0.061382
neu         0.613595
pos         0.325020
compound    0.933231
dtype: float64

### Modelado de topicos

In [15]:
tripadvisor = datos.drop(columns=['Rating'], axis=1).head(2000)

In [16]:
tripadvisor

                                                 Review
0     nice hotel expensive parking got good deal sta...
1     ok nothing special charge diamond member hilto...
2     nice rooms not 4* experience hotel monaco seat...
3     unique, great stay, wonderful time hotel monac...
4     great stay great stay, went seahawk game aweso...
...                                                 ...
1995  best location beach, husband traveled honolulu...
1996  awesome place stay outriiger beach great place...
1997  great time, just returned trip stayed 7 nights...
1998  best location value properties waikiki head ho...
1999  really enjoyed property great terrific locatio...

[2000 rows x 1 columns]

In [17]:
print("Stemms - NLTK")
english_stemmer = SnowballStemmer('english')

Stemms - NLTK

In [18]:
trip_tok = []
for frase in tripadvisor['Review']:
    trip_tok.append(nltk.word_tokenize(frase.lower()))

stems = []    

for frase in trip_tok:
    for palabra in frase:
        result = english_stemmer.stem(palabra)
        stems.append(result)

In [7]:
frases = []
for frase in stems: 
    frases.append(' '.join(frase))

In [11]:
vectorizer = CountVectorizer(stop_words=stopwords, lowercase=True)

BOW=vectorizer.fit_transform(stems)

In [12]:
vocab_BOW = vectorizer.get_feature_names()
matrix_BOW=pd.DataFrame(BOW.toarray(), columns=vocab_BOW)
matrix_BOW

C:\Users\User\anaconda3\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

,00,000,00am,00for,00p,00pm,00usd,01,02,03,...,zero,zillion,zip,zishan,zoe,zombi,zone,zoo,äcor,ærom
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
192255,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192256,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192257,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192258,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
192259,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [16]:
from sklearn.decomposition import LatentDirichletAllocation
number_of_topics = 10

model = LatentDirichletAllocation(n_components=number_of_topics, random_state=0)
model.fit(BOW)

LatentDirichletAllocation(random_state=0)

In [17]:
def display_topics(model, feature_names, no_top_words):
    topic_dict = {}
    for topic_idx, topic in enumerate(model.components_):
        topic_dict["Topic %d words" % (topic_idx)]= ['{}'.format(feature_names[i])
                        for i in topic.argsort()[:-no_top_words - 1:-1]]
        topic_dict["Topic %d weights" % (topic_idx)]= ['{:.1f}'.format(topic[i])
                        for i in topic.argsort()[:-no_top_words - 1:-1]]
    return pd.DataFrame(topic_dict)

In [18]:
no_top_words = 10
display_topics(model, vocab_BOW, no_top_words)

,Topic 0 words,Topic 0 weights,Topic 1 words,Topic 1 weights,Topic 2 words,Topic 2 weights,Topic 3 words,Topic 3 weights,Topic 4 words,Topic 4 weights,Topic 5 words,Topic 5 weights,Topic 6 words,Topic 6 weights,Topic 7 words,Topic 7 weights,Topic 8 words,Topic 8 weights,Topic 9 words,Topic 9 weights
0,night,1373.1,hotel,5158.1,stay,2992.1,nice,1201.1,servic,903.1,great,1929.1,locat,1488.1,staff,1467.1,room,4843.1,small,682.1
1,restaur,643.1,bed,860.1,car,442.1,clean,918.1,walk,870.1,day,905.1,breakfast,743.1,place,1015.1,good,1120.1,floor,535.1
2,review,429.1,love,597.1,shop,376.1,help,745.1,like,815.1,friend,785.1,street,559.1,time,962.1,littl,515.1,need,491.1
3,new,406.1,bathroom,593.1,lobbi,364.1,check,627.1,park,734.1,book,550.1,recommend,519.1,area,601.1,coffe,322.1,best,379.1
4,food,348.1,got,429.1,morn,356.1,comfort,594.1,desk,656.1,make,427.1,close,380.1,want,525.1,travel,305.1,door,361.1
5,better,331.1,use,424.1,san,348.1,realli,579.1,price,590.1,excel,420.1,away,373.1,look,512.1,come,251.1,trip,358.1
6,work,320.1,bar,355.1,peopl,347.1,view,508.1,th,589.1,seattl,413.1,wonder,369.1,free,487.1,10,248.1,nois,348.1
7,visit,296.1,perfect,327.1,expect,319.1,ask,392.1,right,431.1,return,361.1,way,361.1,block,438.1,go,221.1,lot,336.1
8,beauti,241.1,larg,317.1,bit,315.1,thing,333.1,arriv,405.1,minut,312.1,definit,334.1,citi,408.1,extrem,206.1,francisco,305.1
9,told,229.1,went,263.1,inn,308.1,size,232.1,enjoy,368.1,tri,303.1,squar,326.1,problem,315.1,took,201.1,busi,303.1