### Importamos librerias

In [20]:
### Importación de librerías

import spacy
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

nlp = spacy.load("es_core_news_lg")

In [19]:
texto_hotel = pd.read_csv("/Users/juan/Documents/Juan's MacBook Pro/CUNEF/Quinto/Informacion no Estructurada/Practica 1/hotel.csv",)

In [43]:
stopwords = nlp.Defaults.stop_words
print("Hay", str(len(stopwords)), "stopwords")

Hay 551 stopwords

In [36]:
texto_hotel["text"] = texto_hotel["text"].str.lower()

In [51]:
texto_hotel['text_without_stopwords'] = texto_hotel["text"].apply(lambda x: ' '.join([word for word in x.split() if word not in (stopwords)]))
texto_hotel

,text,label,text_without_stopwords
0,es un gran hotel; el mejor de asunción. buenas...,3,hotel; asunción. habitaciones; gente maravillo...
1,hola. no suelo criticar jamas lo que paso pero...,3,hola. suelo criticar jamas paso animo a hacerl...
2,escogi meses antes de mi boda una habitacion p...,3,escogi meses boda habitacion sesion fotos; est...
3,voy a se lo mas equitativo posible; porque soy...,3,a equitativo posible; persona intencionada; en...
4,esta es una experiencia de septiembre de 2016;...,3,experiencia septiembre 2016; cambiaronreservé ...
...,...,...,...
195,excelente atención; instalaciones; comodidad; ...,5,excelente atención; instalaciones; comodidad; ...
196,realmente disfrutamos en pareja por 2 noches d...,5,realmente disfrutamos pareja 2 noches hotel fa...
197,muy buena excelente; muy buena ubicación; cerc...,5,excelente; ubicación; centros comerciales; per...
198,pasé con mi familia la celebración del año nue...,5,pasé familia celebración año nuevo. sobrepasad...
199,la amabilidad de todo el personal (sin excepci...,5,amabilidad personal (sin excepción) hotel dest...

In [53]:
vectorizer = CountVectorizer(max_features=20)
BOW = vectorizer.fit_transform(texto_hotel['text'])

vocab = vectorizer.get_feature_names_out()
pd.DataFrame(BOW.toarray(), columns=vocab)
# .sum().sort_values(ascending = False)[:20]

,con,de,del,desayuno,el,en,es,excelente,hotel,la,las,lo,los,muy,no,para,personal,que,un,una
0,0,1,0,0,7,2,5,1,2,2,0,1,0,1,0,1,0,2,3,2
1,4,17,4,0,11,8,4,0,4,19,5,4,3,2,6,2,1,16,4,2
2,0,4,0,0,2,1,0,0,1,1,1,0,0,1,0,1,0,3,0,1
3,0,2,0,0,1,1,1,0,0,3,0,1,0,0,0,0,0,2,1,1
4,5,20,6,0,16,7,1,0,6,25,4,5,2,2,14,8,2,34,5,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,1,1,0,0,0,1,0,1,0,0,0,0,1,3,0,0,2,0,0,0
196,2,6,3,1,6,1,1,3,1,6,0,3,1,0,0,2,2,4,1,3
197,0,4,0,1,0,0,0,1,0,0,0,0,0,5,0,0,1,0,0,0
198,1,3,2,0,3,0,1,0,1,4,0,1,1,0,0,0,0,3,0,0
199,0,2,0,0,1,0,1,0,1,5,1,0,1,0,0,0,1,1,0,0

In [54]:
tfifd_vec = TfidfVectorizer(max_features=20)
TFIDF = tfifd_vec.fit_transform(texto_hotel["text"])

vocab = tfifd_vec.get_feature_names_out()
pd.DataFrame(TFIDF.toarray(), columns=vocab)
# .sum().sort_values(ascending = False)[:20]

,con,de,del,desayuno,el,en,es,excelente,hotel,la,las,lo,los,muy,no,para,personal,que,un,una
0,0.000000,0.081406,0.000000,0.000000,0.590522,0.177638,0.510090,0.125227,0.190191,0.163641,0.000000,0.133650,0.000000,0.087000,0.000000,0.135470,0.000000,0.201811,0.334947,0.278525
1,0.139741,0.415572,0.145796,0.000000,0.278658,0.213371,0.122540,0.000000,0.114225,0.466826,0.195419,0.160535,0.118024,0.052250,0.261945,0.081360,0.038330,0.484814,0.134108,0.083638
2,0.000000,0.582945,0.000000,0.000000,0.302050,0.159007,0.000000,0.000000,0.170244,0.146478,0.233006,0.000000,0.000000,0.155751,0.000000,0.242523,0.000000,0.541935,0.000000,0.249313
3,0.000000,0.361696,0.000000,0.000000,0.187411,0.197316,0.226639,0.000000,0.000000,0.545305,0.000000,0.296912,0.000000,0.000000,0.000000,0.000000,0.000000,0.448335,0.248035,0.309379
4,0.107597,0.301157,0.134711,0.000000,0.249669,0.115003,0.018871,0.000000,0.105540,0.378362,0.096299,0.123608,0.048467,0.032185,0.376490,0.200465,0.047222,0.634601,0.103260,0.154558
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.264004,0.184733,0.000000,0.000000,0.000000,0.201555,0.000000,0.284173,0.000000,0.000000,0.000000,0.000000,0.297299,0.592280,0.000000,0.000000,0.579323,0.000000,0.000000,0.000000
196,0.174738,0.366811,0.273465,0.094044,0.380122,0.066702,0.076614,0.282132,0.071416,0.368677,0.000000,0.301110,0.098388,0.000000,0.000000,0.203472,0.191720,0.303116,0.083847,0.313754
197,0.000000,0.556064,0.000000,0.213848,0.000000,0.000000,0.000000,0.213848,0.000000,0.000000,0.000000,0.000000,0.000000,0.742843,0.000000,0.000000,0.217978,0.000000,0.000000,0.000000
198,0.173546,0.364307,0.362131,0.000000,0.377528,0.000000,0.152183,0.000000,0.141857,0.488214,0.000000,0.199370,0.195433,0.000000,0.000000,0.000000,0.000000,0.451571,0.000000,0.000000
199,0.000000,0.307128,0.000000,0.000000,0.159137,0.000000,0.192446,0.000000,0.179388,0.771727,0.245521,0.000000,0.247138,0.000000,0.000000,0.000000,0.240789,0.190348,0.000000,0.000000

### Viendo que la mayoria de las palabras mas frecuentes son stopwords, vamos a realizar el mismo analisis pero con la columna sin stopwords

In [55]:
BOW = vectorizer.fit_transform(texto_hotel['text_without_stopwords'])

vocab = vectorizer.get_feature_names_out()
pd.DataFrame(BOW.toarray(), columns=vocab)

,agradable,amable,asunción,atencion,atención,calidad,comida,decoración,desayuno,excelente,habitacion,habitaciones,habitación,hotel,noche,personal,recomendable,restaurante,servicio,ubicación
0,0,0,1,0,0,0,1,0,0,1,0,1,0,2,0,0,0,0,1,0
1,0,0,0,1,0,0,0,0,0,0,2,0,0,4,1,1,0,0,0,0
2,0,0,0,0,1,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0
3,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,6,5,2,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,2,0,0,0,1
196,1,0,0,0,0,0,0,1,1,3,0,0,1,1,0,2,0,2,1,1
197,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,2,1
198,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0
199,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,1,0,0,0,1

In [56]:
TFIDF = tfifd_vec.fit_transform(texto_hotel['text_without_stopwords'])

vocab = tfifd_vec.get_feature_names_out()
pd.DataFrame(TFIDF.toarray(), columns=vocab)

,agradable,amable,asunción,atencion,atención,calidad,comida,decoración,desayuno,excelente,habitacion,habitaciones,habitación,hotel,noche,personal,recomendable,restaurante,servicio,ubicación
0,0.000000,0.000000,0.461803,0.000000,0.000000,0.000000,0.472307,0.000000,0.000000,0.302814,0.000000,0.362235,0.000000,0.459906,0.000000,0.000000,0.0,0.000000,0.359500,0.000000
1,0.000000,0.000000,0.000000,0.308052,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.692762,0.000000,0.000000,0.534266,0.328027,0.179284,0.0,0.000000,0.000000,0.000000
2,0.000000,0.000000,0.000000,0.000000,0.465075,0.000000,0.000000,0.000000,0.000000,0.000000,0.718603,0.436500,0.000000,0.277098,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
3,0.000000,0.000000,0.000000,0.750532,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.660834,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
4,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.425838,0.871516,0.190531,0.0,0.151065,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.000000,0.499529,0.000000,0.000000,0.373956,0.000000,0.000000,0.000000,0.000000,0.293405,0.000000,0.000000,0.000000,0.000000,0.000000,0.598141,0.0,0.000000,0.000000,0.408372
196,0.281016,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.281016,0.165058,0.495175,0.000000,0.000000,0.254537,0.125343,0.000000,0.336492,0.0,0.533585,0.195957,0.229735
197,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.306946,0.306946,0.000000,0.000000,0.000000,0.000000,0.000000,0.312873,0.0,0.000000,0.728809,0.427219
198,0.000000,0.000000,0.000000,0.000000,0.000000,0.657813,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.320271,0.000000,0.000000,0.0,0.681695,0.000000,0.000000
199,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.535836,0.000000,0.340158,0.000000,0.456588,0.0,0.000000,0.000000,0.623458

En este caso ya se puede observar que las palabras con mas importancia segun el BOW y TFIDF son palabras que nos dicen algo sobre las reviews que estamos analizando. Podemos observar que elementos de la experiencia del hotel son los que mas destacan los cliente. Además, todos los adjetivos entre las palabras as importantes son postivos (agradable, amable, excelente, etc.)

In [61]:
esp = open("/Users/juan/Documents/Juan's MacBook Pro/CUNEF/Quinto/Informacion no Estructurada/Practica 1/esp.txt")